<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/10/15 19:02:14
$this->security = array (
  'modificarestrenos' => 
  array (
    'is_secure' => 'on',
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
