<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/10/15 19:04:32
$this->security = array (
  'index' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 1,
        1 => 2,
      ),
    ),
  ),
  'edit' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 1,
        1 => 2,
      ),
    ),
  ),
  'new' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 1,
        1 => 2,
      ),
    ),
  ),
  'alquilarpeliculas' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 1,
        1 => 2,
      ),
    ),
  ),
  'borrarreservas' => 
  array (
    'is_secure' => 'on',
  ),
  'peliculasreservadas' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 1,
        1 => 2,
      ),
    ),
  ),
  'reservarpelicula' => 
  array (
    'is_secure' => 'on',
  ),
  'reservadas' => 
  array (
    'is_secure' => 'on',
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
