<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/10/12 15:16:10
$this->security = array (
  'alquiladas' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 1,
        1 => 2,
      ),
    ),
  ),
  'index' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 1,
        1 => 2,
      ),
    ),
  ),
  'new' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 1,
        1 => 2,
      ),
    ),
  ),
  'edit' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 1,
        1 => 2,
      ),
    ),
  ),
  'devolverpeliculas' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 1,
        1 => 2,
      ),
    ),
  ),
  'modificarestrenos' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 1,
        1 => 2,
      ),
    ),
  ),
  'segunestados' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 1,
        1 => 2,
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
